name: Build Custom ROM for Xiaomi 11T Pro (vili)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04  # Purana Ubuntu version use karenge jisme saari dependencies available hain

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf lib32ncurses-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc zip zlib1g-dev

      - name: Install Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Sync Source Code & Trees
        run: |
          mkdir -p ~/rom && cd ~/rom
          repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs
          git clone https://github.com/LineageOS/android_device_xiaomi_vili.git -b lineage-20.0 device/xiaomi/vili
          git clone https://github.com/The-Muppets/proprietary_vendor_xiaomi_vili.git -b lineage-20.0 vendor/xiaomi/vili
          git clone https://github.com/LineageOS/android_kernel_xiaomi_sm8350.git -b lineage-20.0 kernel/xiaomi/sm8350

      - name: Build ROM
        run: |
          cd ~/rom
          source build/envsetup.sh
          lunch lineage_vili-userdebug
          mka bacon -j$(nproc --all)
